### PR TITLE
prettier

### PR DESCRIPTION
**Pull request by wdhdev**

### CODE REVIEW

**Comment by wdhdev** [comment]
So I can read the code better.

**Comment by MaskDuck** [comment]
uglier when

**Comment by MaskDuck** [comment]
image
tbh i dont like the spaces, but if it's JS standards then it's fine

**Comment by wdhdev** [comment]
> image
> tbh i dont like the spaces, but if it's JS standards then it's fine

I don't like it much either, but it is the default in prettier. I just ran it purely so I can read the code better.

**Pull request merged**
